import { Roboto } from 'next/font/google'

const inter = Roboto({ subsets: ['latin'], weight:[ '400', '500', '700' ]})

export const metadata = {
  title: 'CMS App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
